services:
  # Databases for microservices
  patient-ms-db:
    image: mysql:latest
    container_name: patient-ms-db
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - patient-ms-db-data:/var/lib/mysql
    networks:
      - medilabo-network

  medical-note-ms-db:
    image: mongo:latest
    container_name: medical-note-ms-db
    env_file:
      - .env
    ports:
      - "27018:27017"
    volumes:
      - medical-note-ms-db-data:/data/db
      - ./medical-note-microservice/src/main/resources/mongo-seed:/docker-entrypoint-initdb.d:ro
    networks:
      - medilabo-network

  # Microservices
  # Gateway microservice
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway-microservice
    env_file:
      - .env
    ports:
      - "9001:9001"
    networks:
      - medilabo-network

volumes:
  patient-ms-db-data:
  medical-note-ms-db-data:

networks:
  medilabo-network: