server:
  port: 9102
spring:
  application:
    name: medical-note-microservice
  data:
    mongodb:
      host: localhost
      port: 27018
      database: medicalnotedb
      authentication-database: admin
      username: root
      password: example
security:
  jwt:
    gateway-shared-secret: ${AUTH_JWT_SECRET:change-me-this-secret-should-be-long-32-chars}
    gateway-shared-issuer: ${AUTH_JWT_ISSUER:medilabo-gateway}
