spring:
  cloud:
    openfeign:
      client:
        config:
          patient-microservice:
            url: http://localhost:9101
            connectTimeout: 5000
            readTimeout: 5000
          medical-note-microservice:
            url: http://localhost:9102
            connectTimeout: 5000
            readTimeout: 5000
logging:
  level:
    com.medilabo: debug